title: MetaParticles
description: >- # this means to ignore newlines until "baseurl:"
  Here you will find collection of personal notes on various topics. 
  Note formats can range from simple markup files, repl.it snippets, links to OneNote notebooks as well as Jupyter notebooks. 
  Dockerfiles will be provided wherever neccessary.

github_username: metaparticles

destination: ./docs

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-last-modified-at
  - jekyll-theme-primer-0.5.3

sass:
    sass_dir: ./assets/scss

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

